# Generated by Django 4.1.4 on 2022-12-17 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FetchTime",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fetch_time", models.DateTimeField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Server",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="GPUInfo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("device_id", models.IntegerField()),
                ("pid", models.IntegerField(null=True)),
                ("username", models.CharField(max_length=32, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fetch_time_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gpuser.fetchtime",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="fetchtime",
            name="server_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="gpuser.server"
            ),
        ),
    ]
